name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python  
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies  
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run migrations
      run: |
        python manage.py migrate
      
    - name: Collect static files
      run: |  
        python manage.py collectstatic --no-input
    - name: Build Docker image
      run: |  
        docker build -t django-app .
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker image  
      run: |
        docker tag django-app gabeokiri/django-app:latest
        docker push gabeokiri/django-app:latest

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@master

    - name: Authenticate to GKE  
      uses: google-github-actions/get-gke-credentials@main
      with: 
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        gcloud deployment-manager deployments create my-deployment \
          --template=template-file  
      
    - name: Add secrets
      uses: google-github-actions/get-secretmanager-secrets@main
      with:
        secrets: app-secret   
      
    - name: Expose service
      run: |
        kubectl expose deployment/deployment-name \
          --type=LoadBalancer \
          --port 80 \
          --target-port 8080