name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python  
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies  
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run migrations
      run: |
        python manage.py migrate
      
    - name: Collect static files
      run: |  
        python manage.py collectstatic --no-input
    - name: Build Docker image
      run: |  
        docker build -t django-app .
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker image  
      run: |
        docker tag django-app gabeokiri/django-app:latest
        docker push gabeokiri/django-app:latest
    # - name: Deploy to production server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }} 
    #     key: ${{ secrets.SERVER_KEY }}
    #     script: |
    #       sudo systemctl stop gunicorn
    #       sudo systemctl start gunicornclar